name: build-and-release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pyttsx3 requests

      - name: Build Windows executable
        run: |
          pyinstaller --onefile --noconsole --name YouthfulQuoteGenerator youthful-quote-generator.py

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: YouthfulQuoteGenerator-exe
          path: dist/YouthfulQuoteGenerator.exe

      - name: Publish GitHub release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: dist/YouthfulQuoteGenerator.exe
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
